# Generated by Django 5.1 on 2024-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_id', models.CharField(max_length=75, verbose_name='Código GA')),
            ],
            options={
                'verbose_name': 'Google Analytics',
                'verbose_name_plural': 'Google Analytics',
            },
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nome do Script')),
                ('script', models.TextField(help_text='Adicione o script completo, inclusive com as tags <script></script>.', verbose_name='Script')),
                ('place', models.CharField(choices=[('HD', 'Head/Cabeçalho'), ('FT', 'Footer/Rodapé')], help_text='Escolha onde o script deve ser inserido.', max_length=2, verbose_name='Local')),
                ('is_active', models.BooleanField(default=True, help_text='Os scripts inativos deixarão de ser inseridos nas páginas.', verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
            },
        ),
        migrations.CreateModel(
            name='SEOHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Meta descrição')),
                ('meta_keywords', models.CharField(help_text='Separadas por virgula', max_length=255, verbose_name='Palavras chaves')),
            ],
            options={
                'verbose_name': 'SEO Home',
                'verbose_name_plural': 'SEO Home',
            },
        ),
    ]
