# Generated by Django 5.1 on 2024-09-19 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadro', models.CharField(max_length=100, verbose_name='Quadro')),
                ('descQuadro', models.TextField(max_length=350, verbose_name='Descrição Quadro')),
                ('valor', models.CharField(max_length=20, verbose_name='Valor')),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=False, verbose_name='Publicar Quadro?')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_quadros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quadros',
                'verbose_name_plural': 'Quadros',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='QuadrosComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quadros.quadroscomentario')),
                ('quadros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros_comentario', to='quadros.quadros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_comentario_quadros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='QuadrosImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='quadros-quadros/', verbose_name='Imagem Anexo')),
                ('quadros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros_imagens', to='quadros.quadros')),
            ],
        ),
    ]
