# Generated by Django 5.1 on 2024-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemforum',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
